# Generated by Django 3.1.7 on 2021-03-19 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_auto_20210312_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=80)),
                ('building', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=3)),
                ('receiver_full_name', models.CharField(max_length=60)),
                ('receiver_phone_number', models.CharField(max_length=20)),
                ('is_done', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.merchant')),
            ],
        ),
    ]
