# Generated by Django 3.1.7 on 2021-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_recieved',
            field=models.BooleanField(default=False),
        ),
    ]
