# Generated by Django 3.1.7 on 2021-04-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210327_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_recieved',
        ),
    ]
