# Generated by Django 3.1.7 on 2021-03-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210312_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('is_auth', models.BooleanField(default=False)),
                ('merchant', models.ManyToManyField(to='users.Merchant')),
            ],
        ),
    ]
