# Generated by Django 3.1.7 on 2021-03-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210330_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_auth',
        ),
    ]
