# Generated by Django 3.1.7 on 2021-03-12 07:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dirver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.merchant')),
            ],
        ),
    ]
