# Generated by Django 3.1.7 on 2021-03-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='dirver',
            new_name='driver',
        ),
    ]
