# Generated by Django 3.1.7 on 2021-03-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210312_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='token',
            name='merchant',
        ),
    ]
