# Generated by Django 3.1.7 on 2021-03-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210312_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.merchant'),
            preserve_default=False,
        ),
    ]
